require("user.launch")
require("user.options")
require("user.keymaps")

spec("user.colorscheme")
spec("user.devicons")
spec("user.treesitter")
spec("user.mason")
spec("user.schemastore")
spec("user.lspconfig")
spec("user.lsp-zero")
spec("user.cmp-lua")
spec("user.neo-tree")
spec("user.none-ls")
spec("user.alpha")
spec("user.telescope")
spec("user.lualine")
spec("user.aerial")
spec("user.copilot")
spec("user.toggleterm")
spec("user.trouble")
spec("user.comment")
spec("user.gopher")
-- spec("user.auto-save")
require("user.lazy")
